
#改变默认的静态资源路径
#spring:
#  mvc:
#    static-path-pattern: /res/**     这个会导致welcome page功能失效

#静态资源访问前缀
#resources:
#  static-locations: [classpath:/haha/]


#spring:
#  contentnegotiation:
#    favor-parameter: true  #开启请求参数内容协商模式